db.songDemo.insertMany(
[
  {
    "songId": "S001",
    "title": "Shape of You",
    "artist": "Ed Sheeran",
    "composer": "Ed Sheeran",
    "lyricist": "Ed Sheeran",
    "genre": "English",
    "language": "English",
    "label": "Asylum Records",
    "videoId": "JGwWNGJdvx8",
    "lyrics": "la la random text",
    "isPopular": true,
    "dateTime": "2024-01-01T10:00:00"
  },
  {
    "songId": "S002",
    "title": "Blinding Lights",
    "artist": "The Weeknd",
    "composer": "Abel Tesfaye",
    "lyricist": "Abel Tesfaye",
    "genre": "Hindi Album",
    "language": "English",
    "label": "XO",
    "videoId": "4NRXx6U8ABQ",
    "lyrics": "random lyrics here",
    "isPopular": true,
    "dateTime": "2024-01-02T10:00:00"
  },
  {
    "songId": "S003",
    "title": "Bohemian Rhapsody",
    "artist": "Queen",
    "composer": "Freddie Mercury",
    "lyricist": "Freddie Mercury",
    "genre": "Hindi Album",
    "language": "English",
    "label": "EMI",
    "videoId": "fJ9rUzIMcZQ",
    "lyrics": "random words",
    "isPopular": true,
    "dateTime": "2024-01-03T10:00:00"
  },
  {
    "songId": "S004",
    "title": "Hotel California",
    "artist": "Eagles",
    "composer": "Don Felder",
    "lyricist": "Don Henley",
    "genre": "Hindi Album",
    "language": "English",
    "label": "Asylum",
    "videoId": "EqPtz5qN7HM",
    "lyrics": "placeholder text",
    "isPopular": true,
    "dateTime": "2024-01-04T10:00:00"
  },
  {
    "songId": "S005",
    "title": "Tum Hi Ho",
    "artist": "Arijit Singh",
    "composer": "Mithoon",
    "lyricist": "Mithoon",
    "genre": "Hindi Album",
    "language": "Hindi",
    "label": "T-Series",
    "videoId": "IJq0yyWug1k",
    "lyrics": "random hindi",
    "isPopular": true,
    "dateTime": "2024-01-05T10:00:00"
  },
  {
    "songId": "S006",
    "title": "Kesariya",
    "artist": "Arijit Singh",
    "composer": "Pritam",
    "lyricist": "Amitabh Bhattacharya",
    "genre": "English",
    "language": "Hindi",
    "label": "Sony Music",
    "videoId": "BddP6PYo2gs",
    "lyrics": "random text",
    "isPopular": true,
    "dateTime": "2024-01-06T10:00:00"
  },
  {
    "songId": "S007",
    "title": "Tumi Jake Bhalobasho",
    "artist": "Imran Mahmudul",
    "composer": "Imran",
    "lyricist": "Snahashish Ghosh",
    "genre": "Nasheed",
    "language": "Bangla",
    "label": "CMV",
    "videoId": "eN6AYHAT8UM",
    "lyrics": "random bangla",
    "isPopular": true,
    "dateTime": "2024-01-07T10:00:00"
  },
  {
    "songId": "S008",
    "title": "Amar Sonar Bangla",
    "artist": "Various",
    "composer": "Rabindranath Tagore",
    "lyricist": "Rabindranath Tagore",
    "genre": "Nasheed",
    "language": "Bangla",
    "label": "National",
    "videoId": "cG6rX7K4tN8",
    "lyrics": "random patriotic",
    "isPopular": true,
    "dateTime": "2024-01-08T10:00:00"
  },
  {
    "songId": "S009",
    "title": "Afreen Afreen",
    "artist": "Rahat Fateh Ali Khan",
    "composer": "Nusrat Fateh Ali Khan",
    "lyricist": "Javed Akhtar",
    "genre": "Nasheed",
    "language": "Urdu",
    "label": "Coke Studio",
    "videoId": "kw4tT7SCmaY",
    "lyrics": "random urdu",
    "isPopular": true,
    "dateTime": "2024-01-09T10:00:00"
  },
  {
    "songId": "S010",
    "title": "Tajdar-e-Haram",
    "artist": "Atif Aslam",
    "composer": "Traditional",
    "lyricist": "Traditional",
    "genre": "Nasheed",
    "language": "Urdu",
    "label": "Coke Studio",
    "videoId": "a18py61_F_w",
    "lyrics": "random nasheed",
    "isPopular": true,
    "dateTime": "2024-01-10T10:00:00"
  },

  {
    "songId": "S011",
    "title": "Perfect",
    "artist": "Ed Sheeran",
    "composer": "Ed Sheeran",
    "lyricist": "Ed Sheeran",
    "genre": "English",
    "language": "English",
    "label": "Atlantic",
    "videoId": "2Vv-BfVoq4g",
    "lyrics": "random love text",
    "isPopular": true,
    "dateTime": "2024-01-11T10:00:00"
  },
  {
    "songId": "S012",
    "title": "Believer",
    "artist": "Imagine Dragons",
    "composer": "Dan Reynolds",
    "lyricist": "Dan Reynolds",
    "genre": "Nasheed",
    "language": "English",
    "label": "Interscope",
    "videoId": "7wtfhZwyrcc",
    "lyrics": "random strong text",
    "isPopular": true,
    "dateTime": "2024-01-12T10:00:00"
  },
  {
    "songId": "S013",
    "title": "Let Her Go",
    "artist": "Passenger",
    "composer": "Mike Rosenberg",
    "lyricist": "Mike Rosenberg",
    "genre": "Bangla Gozol",
    "language": "English",
    "label": "Black Crow",
    "videoId": "RBumgq5yVrA",
    "lyrics": "random folk text",
    "isPopular": true,
    "dateTime": "2024-01-13T10:00:00"
  },
  {
    "songId": "S014",
    "title": "Channa Mereya",
    "artist": "Arijit Singh",
    "composer": "Pritam",
    "lyricist": "Amitabh Bhattacharya",
    "genre": "English",
    "language": "Hindi",
    "label": "Sony Music",
    "videoId": "284Ov7ysmfA",
    "lyrics": "random emotional",
    "isPopular": true,
    "dateTime": "2024-01-14T10:00:00"
  },
  {
    "songId": "S015",
    "title": "Kun Faya Kun",
    "artist": "A.R. Rahman",
    "composer": "A.R. Rahman",
    "lyricist": "Irshad Kamil",
    "genre": "Bangla Gozol",
    "language": "Hindi",
    "label": "T-Series",
    "videoId": "T94PHkuydcw",
    "lyrics": "random sufi",
    "isPopular": true,
    "dateTime": "2024-01-15T10:00:00"
  },

  {
    "songId": "S016",
    "title": "O Re Nil Doriya",
    "artist": "Abdul Jabbar",
    "composer": "Alam Khan",
    "lyricist": "Mukul Chowdhury",
    "genre": "Bangla Gozol",
    "language": "Bangla",
    "label": "Bangladesh Betar",
    "videoId": "kH9sJ8X3yK8",
    "lyrics": "random folk bangla",
    "isPopular": true,
    "dateTime": "2024-01-16T10:00:00"
  },
  {
    "songId": "S017",
    "title": "Ei Mon Tomake Dilam",
    "artist": "Sabina Yasmin",
    "composer": "Khan Ataur Rahman",
    "lyricist": "Gazi Mazharul Anwar",
    "genre": "Bangla Gozol",
    "language": "Bangla",
    "label": "Sangeeta",
    "videoId": "ZVh8QK7Rk2E",
    "lyrics": "random classic",
    "isPopular": false,
    "dateTime": "2024-01-17T10:00:00"
  },

  {
    "songId": "S018",
    "title": "Dil Dil Pakistan",
    "artist": "Vital Signs",
    "composer": "Rohail Hyatt",
    "lyricist": "Shoaib Mansoor",
    "genre": "Bangla Gozol",
    "language": "Urdu",
    "label": "EMI Pakistan",
    "videoId": "F7jjpR1G5nI",
    "lyrics": "random patriotic",
    "isPopular": true,
    "dateTime": "2024-01-18T10:00:00"
  },

  {
    "songId": "S019",
    "title": "Kun Anta",
    "artist": "Humood AlKhudher",
    "composer": "Humood",
    "lyricist": "Humood",
    "genre": "Urdu Drama",
    "language": "Arabic",
    "label": "Awakening",
    "videoId": "f7j5u5x2R7Y",
    "lyrics": "random nasheed",
    "isPopular": true,
    "dateTime": "2024-01-19T10:00:00"
  },

  {
    "songId": "S020",
    "title": "Someone Like You",
    "artist": "Adele",
    "composer": "Adele",
    "lyricist": "Adele",
    "genre": "Bangla Geet",
    "language": "English",
    "label": "XL",
    "videoId": "hLQl3WQQoQ0",
    "lyrics": "random sad",
    "isPopular": true,
    "dateTime": "2024-01-20T10:00:00"
  }

  
])

