db.songDemo.insertMany([
  {
    songId: "S051",
    title: "Counting Stars",
    artist: "OneRepublic",
    composer: "Ryan Tedder",
    lyricist: "Ryan Tedder",
    genre: "Bangla Movie",
    language: "English",
    label: "Mosley Music",
    videoId: "hT_nvWreIhg",
    lyrics: "random line text",
    isPopular: true,
    dateTime: "2024-02-01T10:00:00"
  },
  {
    songId: "S052",
    title: "See You Again",
    artist: "Wiz Khalifa",
    composer: "Charlie Puth",
    lyricist: "Charlie Puth",
    genre: "Bangla Movie",
    language: "English",
    label: "Atlantic",
    videoId: "RgKAFK5djSk",
    lyrics: "random text here",
    isPopular: true,
    dateTime: "2024-02-02T10:00:00"
  },
  {
    songId: "S053",
    title: "Zaalima",
    artist: "Arijit Singh",
    composer: "Pritam",
    lyricist: "Amitabh Bhattacharya",
    genre: "Bangla Movie",
    language: "Hindi",
    label: "Sony Music",
    videoId: "YvY9c2yU6n8",
    lyrics: "random romantic",
    isPopular: true,
    dateTime: "2024-02-03T10:00:00"
  },
  {
    songId: "S054",
    title: "Gerua",
    artist: "Arijit Singh",
    composer: "Pritam",
    lyricist: "Amitabh Bhattacharya",
    genre: "Bangla Movie",
    language: "Hindi",
    label: "Sony Music",
    videoId: "AEIVhBS6baE",
    lyrics: "random words",
    isPopular: true,
    dateTime: "2024-02-04T10:00:00"
  },
  {
    songId: "S055",
    title: "Bojhena Shey Bojhena",
    artist: "Arijit Singh",
    composer: "Arindom",
    lyricist: "Prasen",
    genre: "Bangla Movie",
    language: "Bangla",
    label: "SVF",
    videoId: "k4yXQkG2s1E",
    lyrics: "random bangla",
    isPopular: true,
    dateTime: "2024-02-05T10:00:00"
  },
  {
    songId: "S056",
    title: "Mon Majhi Re",
    artist: "Arijit Singh",
    composer: "Indradeep Dasgupta",
    lyricist: "Srijato",
    genre: "Bangla Movie",
    language: "Bangla",
    label: "SVF",
    videoId: "Q7zvZ8cZQ5k",
    lyrics: "random folk",
    isPopular: false,
    dateTime: "2024-02-06T10:00:00"
  },
  {
    songId: "S057",
    title: "Aaj Jaane Ki Zid Na Karo",
    artist: "Farida Khanum",
    composer: "Sohail Rana",
    lyricist: "Fayyaz Hashmi",
    genre: "Bangla Album",
    language: "Urdu",
    label: "EMI Pakistan",
    videoId: "n9Y2Eb8bMvo",
    lyrics: "random ghazal",
    isPopular: true,
    dateTime: "2024-02-07T10:00:00"
  },
  {
    songId: "S058",
    title: "Bhar Do Jholi Meri",
    artist: "Adnan Sami",
    composer: "Pritam",
    lyricist: "Kausar Munir",
    genre: "Bangla Album",
    language: "Urdu",
    label: "T-Series",
    videoId: "dYFf4kE0mJQ",
    lyrics: "random sufi",
    isPopular: true,
    dateTime: "2024-02-08T10:00:00"
  },
  {
    songId: "S059",
    title: "La Ilaha Illallah",
    artist: "Maher Zain",
    composer: "Maher Zain",
    lyricist: "Maher Zain",
    genre: "Bangla Album",
    language: "English",
    label: "Awakening",
    videoId: "uYtR2n0yR1Y",
    lyrics: "random nasheed",
    isPopular: true,
    dateTime: "2024-02-09T10:00:00"
  },
  {
    songId: "S060",
    title: "Numb",
    artist: "Linkin Park",
    composer: "Linkin Park",
    lyricist: "Chester Bennington",
    genre: "Bangla Album",
    language: "English",
    label: "Warner Bros",
    videoId: "kXYiU_JCYtU",
    lyrics: "random rock",
    isPopular: true,
    dateTime: "2024-02-10T10:00:00"
  },
  {
    songId: "S061",
    title: "In The End",
    artist: "Linkin Park",
    composer: "Linkin Park",
    lyricist: "Mike Shinoda",
    genre: "Bangla Album",
    language: "English",
    label: "Warner Bros",
    videoId: "eVTXPUF4Oz4",
    lyrics: "random rock",
    isPopular: true,
    dateTime: "2024-02-11T10:00:00"
  },
  {
    songId: "S062",
    title: "Attention",
    artist: "Charlie Puth",
    composer: "Charlie Puth",
    lyricist: "Charlie Puth",
    genre: "Bangla Folk",
    language: "English",
    label: "Atlantic",
    videoId: "nfs8NYg7yQM",
    lyrics: "random text",
    isPopular: true,
    dateTime: "2024-02-12T10:00:00"
  },
  {
    songId: "S063",
    title: "Hasi Ban Gaye",
    artist: "Ami Mishra",
    composer: "Ami Mishra",
    lyricist: "Kunaal Vermaa",
    genre: "Bangla Folk",
    language: "Hindi",
    label: "Sony Music",
    videoId: "tLqtnGLfm4Q",
    lyrics: "random line",
    isPopular: true,
    dateTime: "2024-02-13T10:00:00"
  },
  {
    songId: "S064",
    title: "Sun Raha Hai",
    artist: "Ankit Tiwari",
    composer: "Ankit Tiwari",
    lyricist: "Sandeep Nath",
    genre: "Bangla Folk",
    language: "Hindi",
    label: "T-Series",
    videoId: "eHnS6I_6F8E",
    lyrics: "random",
    isPopular: true,
    dateTime: "2024-02-14T10:00:00"
  },
  {
    songId: "S065",
    title: "Ami Tomar Kache",
    artist: "Arijit Singh",
    composer: "Jeet Gannguli",
    lyricist: "Prasen",
    genre: "Bangla Folk",
    language: "Bangla",
    label: "SVF",
    videoId: "xw9vK3zR8uE",
    lyrics: "random bangla",
    isPopular: true,
    dateTime: "2024-02-15T10:00:00"
  },
  {
    songId: "S066",
    title: "Pagol Mon",
    artist: "James",
    composer: "James",
    lyricist: "James",
    genre: "Bangla Folk",
    language: "Bangla",
    label: "G-Series",
    videoId: "0F5Yk5g7vY4",
    lyrics: "random",
    isPopular: false,
    dateTime: "2024-02-16T10:00:00"
  },
  {
    songId: "S067",
    title: "Pasoori",
    artist: "Ali Sethi",
    composer: "Ali Sethi",
    lyricist: "Ali Sethi",
    genre: "Hindi Movie",
    language: "Urdu",
    label: "Coke Studio",
    videoId: "5Eqb_-j3FDA",
    lyrics: "random",
    isPopular: true,
    dateTime: "2024-02-17T10:00:00"
  },
  {
    songId: "S068",
    title: "Kun Faya Kun (Reprise)",
    artist: "A.R. Rahman",
    composer: "A.R. Rahman",
    lyricist: "Irshad Kamil",
    genre: "Hindi Movie",
    language: "Hindi",
    label: "T-Series",
    videoId: "T94PHkuydcw",
    lyrics: "random",
    isPopular: true,
    dateTime: "2024-02-18T10:00:00"
  },
  {
    songId: "S069",
    title: "Fix You",
    artist: "Coldplay",
    composer: "Coldplay",
    lyricist: "Chris Martin",
    genre: "Hindi Movie",
    language: "English",
    label: "Parlophone",
    videoId: "k4V3Mo61fJM",
    lyrics: "random",
    isPopular: true,
    dateTime: "2024-02-19T10:00:00"
  },
  {
    songId: "S070",
    title: "Yellow",
    artist: "Coldplay",
    composer: "Coldplay",
    lyricist: "Chris Martin",
    genre: "Hindi Movie",
    language: "English",
    label: "Parlophone",
    videoId: "yKNxeF4KMsY",
    lyrics: "random",
    isPopular: true,
    dateTime: "2024-02-20T10:00:00"
  }
])

